### ISSUE TITLE
$wgFlaggedRevsNamespaces

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#10]
The file namespace should not be in this setting in LocalSettings.php. The module namespace should.

**Comment by Telshin** [comment]
NS_FILE was located in the old LS, should it be removed then?

**Comment by elifoster** [comment]
I'm not sure how you guys have the LS set up, but it should be using namespace integer values, yes? Basically, we should not require files to be accepted because that feature is very broken in the FlaggedRevs extension.

**Comment by retep998** [comment]
It would be nice if Modules worked with the FlaggedRevs extension.

**Comment by elifoster** [comment]
It would. You should go suggest that to the FlaggedRevs devs.

**Comment by Telshin** [comment]
@satanicsanta - The point I was trying to make was that the old LS for FTB had NS_File on it for FlaggedRevs piece. It is doable to remove it, just wanted a double check.

**Comment by elifoster** [comment]
Yeah, we had to add that to fix some issue. I have no recollection of what that issue is, and it seems this is more annoying than useful. So, yes, go ahead and change it, if some issue pops up we will let you know. :)

**Comment by Telshin** [comment]
Removed NS_FILE

**Comment by Telshin** [comment]
Any update on whether NS_FILE is still an issue?

**Comment by retep998** [comment]
I uploaded some new versions of some files a couple days ago and I still had to deal with unaccepting old revisions and then accepting the latest version.
Also, please add the Module namespace. Apparently the extension does support it due to other wikis doing it: https://gerrit.wikimedia.org/r/#/c/62985/2/wmf-config/flaggedrevs.php

**Comment by ghost** [comment]
Can be closed, no longer have FlaggedRevs
