### ISSUE TITLE
Lost ability to change many rights

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#15]
![look at dis :3](http://puu.sh/eaHmn/0d81f03028.png)

I should be able to change staff, translation admin, reviewer, and translation reviewer.

**Comment by Telshin** [comment]
We're making this a priority this morning to fix since the last patch somehow went wonky.

**Comment by noahm** [comment]
Should be fixed now.
