### ISSUE TITLE
Translations cannot be patrolled

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#2]
When patrolling translated versions of pages, it states that the patrol failed.

**Comment by noahm** [comment]
This is an issue that the authors of the Translate extension have been aware of for several years ([T44162](https://phabricator.wikimedia.org/T44162)) but never came to an agreed solution for. I'm currently investigating if this is something that I could reasonably fix and submit back to them.

**Comment by noahm** [comment]
A bug fix is currently up for review by the Translate extension maintainers at https://gerrit.wikimedia.org/r/185101 but may be merged into the gamepedia repo before that ends up going anywhere.

**Comment by Telshin** [comment]
Deployed out this fix. You should be able to do this now.

**Comment by noahm** [comment]
Correction, you will continue not being able to patrol translations. However, the footer prompting you mark a page as patrolled will not appear on translation pages. Instead, the translate extension expects you to use the translation review tools on Special:Translate. If this behavior doesn't suit your use case then we'll have to figure out a different solution.
