### ISSUE TITLE
New Banhammer usergroup

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#21]
We didn't have a use for this before, but now that we have a lot of spam, vandalism, and ads (due to being on a larger site), it's kind of needed. We don't want everyone in the staff group to be able to block, and we don't want everyone to be admins. So,

``` php
$wgGroupPermissions['banhammer']['block'] = true;
```

should be added to LocalSettings.php.

**Comment by Telshin** [comment]
The new group has been created and should be good to go.
