### ISSUE TITLE
Mobile redlinks

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#23]
Redlinks dont appear as red, and are not clickable while using the mobile version of the site

**Comment by noahm** [comment]
See https://www.mediawiki.org/wiki/Thread:Extension_talk:MobileFrontend/Red_links
Because we're working with 1.23 (thus we don't have the options available) I'll have to back-port that option into our current version of MF.

**Comment by noahm** [comment]
Put a fix in that will probably deploy this Wednesday

**Comment by noahm** [comment]
Fix is live as of this afternoon.

**Comment by elifoster** [comment]
Fix is confirmed.
