### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#24]
Please add Nicaraguan Spanish to the Names.php file:

```
$wgExtraLanguageNames['es-ni'] = 'Español (Nicaragua)';
```

**Comment by Telshin** [comment]
Added

**Comment by elifoster** [comment]
Any idea when translating pages to es-ni will be possible?

**Comment by Telshin** [comment]
I have no idea how/what do with that. We recommend reaching out to the content side or checking documentation of the translate extension.

**Comment by elifoster** [comment]
I mean, like, a restart of the wiki or something? I'm not entirely sure how wiki families work vs single wiki sites.

**Comment by Telshin** [comment]
Do you mean opening something like ftb-es.gamepedia?

**Comment by elifoster** [comment]
No no no. Like how if you added a new extension you would need to restart the server for it to actually be usable on the wiki.

**Comment by Telshin** [comment]
We don't have to restart anything? The setting is in place and there.

**Comment by elifoster** [comment]
Oh. That's all I was asking :laughing:

**Comment by elifoster** [comment]
I just realized that the e in espanol should not be capitalized. @Telshin could you change

```
$wgExtraLanguageNames['es-ni'] = 'Español (Nicaragua)';
```

to

```
$wgExtraLanguageNames['es-ni'] = 'español (Nicaragua)';
```

Also, any idea why it is not showing up in the list of languages on Special:Translate?

**Comment by Telshin** [comment]
Done and not off the top of my head.

**Comment by Telshin** [comment]
Special:Translate does not pull in the extra language names. That is why you don't see it on the list, however, you can still go to http://ftb.gamepedia.com/Special:Translate?filter=%21translated&action=translate&language=es-ni to see them.
