### ISSUE TITLE
Semantic Uninstallation

### ISSUE THREAD

**Issue by xbony2** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#28]
So, we have the [Semantic Forms](https://www.mediawiki.org/wiki/Extension:Semantic_Forms) and [Semantic MediaWiki](https://semantic-mediawiki.org) extensions installed to our wiki. However, we do not use it's functions for anything, nor do we plan to, thus it would be appropriate to uninstall it.

**Comment by Chocohead** [comment]
I don't see why it was installed in the first place.

**Comment by xbony2** [comment]
I wondered the same thing- it's apparently an [optional extension](http://help.gamepedia.com/Extension#Optional_allowed_extensions), but I don't think we ever requested it.

**Comment by elifoster** [comment]
@retep998 may have requested it.

**Comment by retep998** [comment]
I didn't request it. I'd be fine with seeing it vanish.

**Comment by elifoster** [comment]
I'm fine with this being uninstalled too. I don't see us ever using it, and its existence might make users think we actually use it.

**Comment by ghost** [comment]
Confirm unused, scanned all pages for any semantics.

**Comment by xbony2** [comment]
Thanks cbutt.
