### ISSUE TITLE
List of things broken in the past couple days

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#34]
- [x] HydraWiki/OreDict#26
- [x] Searching is broken, not really sure how to describe it, just go search for stuff
- [x] Translation extension pack upgrade needed

**Comment by Alexia** [comment]
- Translate/MLEB are updated
- Search is currently in the process of reindexing on all wikis.  Some results are showing up on FTB now and more will when it finishes.
- I put in a ticket to get OreDict upgraded/fixed.

**Comment by elifoster** [comment]
In the meantime for the OreDict thing, could OreDict get its latest commit(s) in master be pulled into the wiki? Right now it's unclear where we are actually at because the version number is the same as it was last year, but it has some of the new things introduced recently.

Translate and search fix confirmed.
