### ISSUE TITLE
$wgAllowCopyUploads should be true

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#4]
LocalSettings.php

**Comment by Telshin** [comment]
This is already setup as true in LS.php

**Comment by elifoster** [comment]
I will work on my code to test it, and let you know the results when I get that all ready.

**Comment by Telshin** [comment]
Sweet!

**Comment by elifoster** [comment]
Only people in the Curse group are allowed to upload files by URL. This needs to be changed.

**Comment by Telshin** [comment]
Use your test script again.

**Comment by elifoster** [comment]
Works.
