### ISSUE TITLE
Spam detection should ignore people in certain groups

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#5]
People in the Editor and Reviewer groups should not trigger spam detection.

**Comment by Telshin** [comment]
Which spam detection are you referring to?

**Comment by elifoster** [comment]
I believe the last one I got was the page blanking one, but those groups really should be ignored for all of it.

**Comment by noahm** [comment]
I assume you're talking about the filters you have configured in Special:AbuseFilter. As best I can tell, Abuse Filter doesn't provide any user rights to allow bypassing its filters. Any exceptions would have to be written into the logic of the filters themselves. If this was previously not the case, then I'm curious what had been configured to allow that type of exception to be made.

**Comment by noahm** [comment]
If you want this behavior on the wiki now, then the current filters should be edited to include something along the lines of `& !("sysop" in user_groups)`

**Comment by elifoster** [comment]
> If this was previously not the case, then I'm curious what had been configured to allow that type of exception to be made.

We did not have an abuse filter before we moved to Gamepedia.

> If you want this behavior on the wiki now, then the current filters should be edited to include something along the lines of `& !("sysop" in user_groups)`

That'd be great, of course, if it was reviewer and editor rather than sysop.

**Comment by noahm** [comment]
Sure, you should be able to edit the filters at [Special:AbuseFilter](http://ftb.gamepedia.com/Special:AbuseFilter) as you see fit. (You are the admin, after all!)

**Comment by elifoster** [comment]
Oh, awesome, I shall do that then.
