### ISSUE TITLE
Reviewer adding/removing

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#6]
Only people in the Curse group can add people to Reviewer. Sysops should be able to do this.

**Comment by Telshin** [comment]
Should be fixed

**Comment by retep998** [comment]
I am a sysop and I am unable to do this.

**Comment by elifoster** [comment]
I am also a sysop and a bureaucrat and I am unable to do this.

**Comment by noahm** [comment]
Should be fixed now.

**Comment by elifoster** [comment]
Thank you, it works again.
