### ISSUE TITLE
Mass-automated edits cause errors

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#9]
503 internal server errors, to be specific.

**Comment by Telshin** [comment]
Is this using a bot or some other tool?

**Comment by elifoster** [comment]
It is using my [bot](https://github.com/satanicsanta/satanicbot).

**Comment by Telshin** [comment]
Which bot because I"ve not heard of others having this issue.

**Comment by elifoster** [comment]
I used a hyperlink in that previous post :P https://github.com/satanicsanta/satanicbot

**Comment by Telshin** [comment]
This can happen with bots especially if a query is taking over 30 seconds in the DB. We have a process that kinda kills those long running processes. I recommend adding in some error handling for those situations.

**Comment by ghost** [comment]
@satanicsanta Which command exactly is causing the issue, I can probably hook something into it to handle errors and return stack traces for processes that are causing it.

**Comment by elifoster** [comment]
@cblair91 t's actually not a command. It's my userlinks thing made to fix the links to all my user and talk pages.

**Comment by ghost** [comment]
@satanicsanta Source code link?

**Comment by elifoster** [comment]
@cblair91 https://github.com/satanicsanta/SatanicBot/blob/master/src/userlinks.pl

**Comment by ghost** [comment]
Should be better error handling, sometimes the server can respond slowly due to CloudFlare, but if it's that case, it'll ignore it now and just continue with the list.

**Comment by ghost** [comment]
@elifoster Any update on if this is better? :)

**Comment by elifoster** [comment]
I have not tested it. I've been on a wiki-vacation for the past few months. If I remember I'll try to run the script when I get home today, though I may forget since I have college orientation tonight.

**Comment by elifoster** [comment]
This was fixed a while ago.
